// Generated by gencpp from file imu_driver/ConvertToQuaternionResponse.msg
// DO NOT EDIT!


#ifndef IMU_DRIVER_MESSAGE_CONVERTTOQUATERNIONRESPONSE_H
#define IMU_DRIVER_MESSAGE_CONVERTTOQUATERNIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace imu_driver
{
template <class ContainerAllocator>
struct ConvertToQuaternionResponse_
{
  typedef ConvertToQuaternionResponse_<ContainerAllocator> Type;

  ConvertToQuaternionResponse_()
    {
    }
  ConvertToQuaternionResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::imu_driver::ConvertToQuaternionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imu_driver::ConvertToQuaternionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ConvertToQuaternionResponse_

typedef ::imu_driver::ConvertToQuaternionResponse_<std::allocator<void> > ConvertToQuaternionResponse;

typedef boost::shared_ptr< ::imu_driver::ConvertToQuaternionResponse > ConvertToQuaternionResponsePtr;
typedef boost::shared_ptr< ::imu_driver::ConvertToQuaternionResponse const> ConvertToQuaternionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imu_driver::ConvertToQuaternionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imu_driver::ConvertToQuaternionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace imu_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::imu_driver::ConvertToQuaternionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_driver::ConvertToQuaternionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_driver::ConvertToQuaternionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_driver::ConvertToQuaternionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_driver::ConvertToQuaternionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_driver::ConvertToQuaternionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imu_driver::ConvertToQuaternionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::imu_driver::ConvertToQuaternionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::imu_driver::ConvertToQuaternionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imu_driver/ConvertToQuaternionResponse";
  }

  static const char* value(const ::imu_driver::ConvertToQuaternionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imu_driver::ConvertToQuaternionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::imu_driver::ConvertToQuaternionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imu_driver::ConvertToQuaternionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConvertToQuaternionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imu_driver::ConvertToQuaternionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::imu_driver::ConvertToQuaternionResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // IMU_DRIVER_MESSAGE_CONVERTTOQUATERNIONRESPONSE_H
