// Generated by gencpp from file imu_driver/ConvertToQuaternionRequest.msg
// DO NOT EDIT!


#ifndef IMU_DRIVER_MESSAGE_CONVERTTOQUATERNIONREQUEST_H
#define IMU_DRIVER_MESSAGE_CONVERTTOQUATERNIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace imu_driver
{
template <class ContainerAllocator>
struct ConvertToQuaternionRequest_
{
  typedef ConvertToQuaternionRequest_<ContainerAllocator> Type;

  ConvertToQuaternionRequest_()
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , w(0.0)  {
    }
  ConvertToQuaternionRequest_(const ContainerAllocator& _alloc)
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , w(0.0)  {
  (void)_alloc;
    }



   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _w_type;
  _w_type w;





  typedef boost::shared_ptr< ::imu_driver::ConvertToQuaternionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imu_driver::ConvertToQuaternionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ConvertToQuaternionRequest_

typedef ::imu_driver::ConvertToQuaternionRequest_<std::allocator<void> > ConvertToQuaternionRequest;

typedef boost::shared_ptr< ::imu_driver::ConvertToQuaternionRequest > ConvertToQuaternionRequestPtr;
typedef boost::shared_ptr< ::imu_driver::ConvertToQuaternionRequest const> ConvertToQuaternionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imu_driver::ConvertToQuaternionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imu_driver::ConvertToQuaternionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::imu_driver::ConvertToQuaternionRequest_<ContainerAllocator1> & lhs, const ::imu_driver::ConvertToQuaternionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.w == rhs.w;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::imu_driver::ConvertToQuaternionRequest_<ContainerAllocator1> & lhs, const ::imu_driver::ConvertToQuaternionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace imu_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::imu_driver::ConvertToQuaternionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_driver::ConvertToQuaternionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_driver::ConvertToQuaternionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_driver::ConvertToQuaternionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_driver::ConvertToQuaternionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_driver::ConvertToQuaternionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imu_driver::ConvertToQuaternionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "65d8d4f0f20a4f15d3f80a0c317b43cd";
  }

  static const char* value(const ::imu_driver::ConvertToQuaternionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x65d8d4f0f20a4f15ULL;
  static const uint64_t static_value2 = 0xd3f80a0c317b43cdULL;
};

template<class ContainerAllocator>
struct DataType< ::imu_driver::ConvertToQuaternionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imu_driver/ConvertToQuaternionRequest";
  }

  static const char* value(const ::imu_driver::ConvertToQuaternionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imu_driver::ConvertToQuaternionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request\n"
"float64 roll\n"
"float64 pitch\n"
"float64 yaw\n"
"\n"
"# Response\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"\n"
;
  }

  static const char* value(const ::imu_driver::ConvertToQuaternionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imu_driver::ConvertToQuaternionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConvertToQuaternionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imu_driver::ConvertToQuaternionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::imu_driver::ConvertToQuaternionRequest_<ContainerAllocator>& v)
  {
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "w: ";
    Printer<double>::stream(s, indent + "  ", v.w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMU_DRIVER_MESSAGE_CONVERTTOQUATERNIONREQUEST_H
